# Generated by Django 3.2.9 on 2021-11-18 18:52

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
    ]
