# Generated by Django 3.2.9 on 2021-11-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0002_alter_customer_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='cashApi.customer'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
