# Generated by Django 3.2.9 on 2021-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0003_auto_20211118_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='json_products',
            field=models.TextField(default=''),
        ),
    ]
