# Generated by Django 3.2.9 on 2021-11-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0004_sale_json_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='json_products',
            new_name='products',
        ),
    ]
