# Generated by Django 3.2.9 on 2021-11-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0007_auto_20211118_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='price',
        ),
    ]
