# Generated by Django 3.2.9 on 2021-11-19 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0009_alter_customer_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='products_bd',
            field=models.ManyToManyField(to='cashApi.Product'),
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 41, 5, 679195)),
        ),
    ]
