# Generated by Django 3.2.9 on 2021-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0011_alter_sale_sold_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(auto_now=True),
        ),
    ]
