# Generated by Django 3.2.9 on 2021-11-19 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0012_alter_sale_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_bd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashApi.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.TextField(default='{"name": "", "document": ""}'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 19, 18, 24, 28, 694339), null=True),
        ),
    ]
