# Generated by Django 3.2.9 on 2021-11-22 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0013_auto_20211119_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chashback',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 11, 51, 47, 200789), null=True),
        ),
    ]
