# Generated by Django 3.2.9 on 2021-11-22 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0014_auto_20211122_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chashback',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 14, 9, 51, 21173)),
        ),
    ]
