# Generated by Django 3.2.9 on 2021-11-22 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0015_auto_20211122_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 14, 9, 55, 234841)),
        ),
    ]
