# Generated by Django 3.2.9 on 2021-11-22 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0021_auto_20211122_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 15, 6, 17, 997928)),
        ),
    ]
