# Generated by Django 3.2.9 on 2021-11-22 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApi', '0024_auto_20211122_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 22, 15, 11, 29, 553013)),
        ),
    ]
